### ISSUE TITLE
Unexpected behaviour in v4 with NixOS

### ISSUE THREAD

**Issue by guttermonk** [luccahuguet/yazelix#24]
I'm running NixOS and previously had v3 running well. I then installed nushell and ran it to generate an environment and config files. Then I cloned the yazelix config files into my .config folder. When I open yazelix v4, it opens with a regular 3-column yazi panel inside of zellij, labeled "sidebar". When I navigate to a text file and open it, helix opens in the sidebar.

Whereas before in v3, when I opened a doc from the sidebar, it opened in a new helix panel.

Am I doing something wrong? Not sure if I need to do something special for NixOS that wasn't in the install instructions. I am able to go back to my old v3 config files and it works as expected again.

I've never really used nushell before, but when I enter `type nu` in terminal, I get:  
`nu is /run/current-system/sw/bin/nu`

Also tried setting the two `.nu` files in the yazi folder to be executable. Anything else I could be missing?

**Comment by guttermonk** [comment]
Figured out the issue - the instructions need an additional step. After cloning the repo into your config, move the zellij folder that's in the `~/,config/yazelix` folder into your `~/.config` folder.

Can someone verify if that's correct? If so, I'd be happy to create a pull request for the README.md file.

**Comment by luccahuguet** [comment]
> When I open yazelix v4, it opens with a regular 3-column yazi panel inside of zellij, labeled "sidebar"
this means yazi is not using the proper yazelix config in `~/.config/yazelix/yazi/sidebar/yazi.toml`

> When I navigate to a text file and open it, helix opens in the sidebar.
odd.

> I am able to go back to my old v3 config files and it works as expected again.
good. I'll see if I add an option on v4 to use the old method, that could mitigate your issue

I will create an issue to add troubleshooting steps, it would be helpful for those with problems..

I 've updated the "installing instructions". Please see if the new instructions take care of your problem... specially related to the moment you call nu / zellij

**Comment by luccahuguet** [comment]
> Figured out the issue - the instructions need an additional step. After cloning the repo into your config, move the zellij folder that's in the `~/,config/yazelix` folder into your `~/.config` folder.
> 
> Can someone verify if that's correct? If so, I'd be happy to create a pull request for the README.md file.

this is not the case... 

I myself have no `~/.config/zellij` folder. 

I only run zellij the yazelix way

to sum it up: all of the config you need should be self contained in the `~/.config/yazelix` folder and self-sufficient. 
Another benefit of this is not messing with the user's default config for zellij or yazi for example

**Comment by luccahuguet** [comment]
thanks btw

I noticed the `Instructions to set it up` were lacking, thanks to your issue

**Comment by guttermonk** [comment]
Thank you for the feedback. With version 3, I was running yazelix with the following command:
`kitty -e zellij -l ~/.config/zellij/layouts/yazelix`

If you don't have a `~/.config/zellij` folder, what command do you use to run yazelix in version 4?

I suppose I could put the zellij config back in the yazelix config folder, and then run it with `kitty -e zellij -l ~/.config/yazelix/zellij/layouts/yazelix` if that's the intended way to run it. Thanks again!

**Comment by guttermonk** [comment]
Nevermind, just saw this in the new instructions:
`nu -c "zellij -l welcome --config-dir ~/.config/yazelix/zellij options --layout-dir ~/.config/yazelix/zellij/layouts"`

Out of curiosity, is there a way to open a specific session directly? This would be extremely useful in Hyprland and NixOS, since I could bind such a command to a keybinding in Hyprland and use it as my primary IDE for editing my Nix config.

**Comment by guttermonk** [comment]
It _is_ working now. Thank you.

That's correct - by session, I mean Zellij session. I haven't really used Zellij before, but if there'd be a way to open a Zellij session with yazelix that'd really cool.

**Comment by luccahuguet** [comment]
> It _is_ working now. Thank you.

Cool! We can close this issue then

> That's correct - by session, I mean Zellij session. I haven't really used Zellij before, but if there'd be a way to open a Zellij session with yazelix that'd really cool.

well, if you're already in a session, you can just hit `ctrl e`, then `w` and voilá, you opened the session manager

and from outside zellij you could `zellij attach <SESSION_NAME>` (and map it to a keybinding)

maybe ` wezterm -e zellij attach <SESSION_NAME>` (i just tested this and it seems to work)

**Comment by guttermonk** [comment]
It works! This is great. Thanks for your help, and I appreciate the `Instructions to set it up` update. You're the best.
