### ISSUE TITLE
Could you please help add a tutorial or section how to use?

### ISSUE THREAD

**Issue by Rope-a-dope** [luccahuguet/yazelix#39]
Thank you so much for your great work! I just installed it, but I am kind of lost on how to use it. Could you please help add a tutorial or section how to use? Thank you!

**Comment by luccahuguet** [comment]
hi there! You're welcome, and thank you for creating an issue

we could add a section to the readme "Im lost, too much information"

and what I would put there is some brief information guiding the person to learn more about the individual components of yazelix. the closest we have now is https://github.com/luccahuguet/yazelix#discoverability-of-keybindings

but my suggestion for you is to read a bit more of zellij's documentation and use zellij, move around, even without yazelix, just zellij on its own, its a big part of the feeling...

anything specific you want to know more about?

in the future I'll post a video on X about how to use it

**Comment by Rope-a-dope** [comment]
> hi there! You're welcome, and thank you for creating an issue
> 
> we could add a section to the readme "Im lost, too much information"
> 
> and what I would put there is some brief information guiding the person to learn more about the individual components of yazelix. the closest we have now is https://github.com/luccahuguet/yazelix#discoverability-of-keybindings
> 
> but my suggestion for you is to read a bit more of zellij's documentation and use zellij, move around, even without yazelix, just zellij on its own, its a big part of the feeling...
> 
> anything specific you want to know more about?
> 
> in the future I'll post a video on X about how to use it

Thank you so much for your hep! Just general use. I will learn Zellij first. Thanks  a lot!

**Comment by luccahuguet** [comment]
I will close this when I add something similar to what I told you to the readme

**Comment by luccahuguet** [comment]
You're welcome!

**Comment by luccahuguet** [comment]
added
